({
  config: {
    menu: {
      label: 'Select2',
      icon: 'bx bx-list-ul',
    },
  },
  col: 'user',
  id: ({ user }) => [user._id],
  tpl: () => [
    H4(
      { class: 'fw-bold py-3 mb-4' },
      SPAN({ class: 'text-muted fw-light' }, SPAN({ text: 'Forms /' })),
      SPAN({ text: ' Selects and tags' }),
    ),
    DIV(
      { class: 'row' },
      DIV(
        { class: 'col-12' },
        DIV(
          { class: 'card mb-4' },
          H5({ class: 'card-header' }, SPAN({ text: 'Select2' })),
          DIV(
            { class: 'card-body' },
            DIV(
              { class: 'row' },
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'select2Basic', class: 'form-label' }, SPAN({ text: 'Basic' })),
                SELECT(
                  {
                    id: 'select2Basic',
                    class: 'select2 form-select form-select-lg',
                    'data-allow-clear': 'true',
                  },
                  OPTION({ value: 'AK' }, SPAN({ text: 'Alaska' })),
                  OPTION({ value: 'HI' }, SPAN({ text: 'Hawaii' })),
                  OPTION({ value: 'CA' }, SPAN({ text: 'California' })),
                  OPTION({ value: 'NV' }, SPAN({ text: 'Nevada' })),
                  OPTION({ value: 'OR' }, SPAN({ text: 'Oregon' })),
                  OPTION({ value: 'WA' }, SPAN({ text: 'Washington' })),
                  OPTION({ value: 'AZ' }, SPAN({ text: 'Arizona' })),
                  OPTION({ value: 'CO' }, SPAN({ text: 'Colorado' })),
                  OPTION({ value: 'ID' }, SPAN({ text: 'Idaho' })),
                  OPTION({ value: 'MT' }, SPAN({ text: 'Montana' })),
                  OPTION({ value: 'NE' }, SPAN({ text: 'Nebraska' })),
                  OPTION({ value: 'NM' }, SPAN({ text: 'New Mexico' })),
                  OPTION({ value: 'ND' }, SPAN({ text: 'North Dakota' })),
                  OPTION({ value: 'UT' }, SPAN({ text: 'Utah' })),
                  OPTION({ value: 'WY' }, SPAN({ text: 'Wyoming' })),
                  OPTION({ value: 'AL' }, SPAN({ text: 'Alabama' })),
                  OPTION({ value: 'AR' }, SPAN({ text: 'Arkansas' })),
                  OPTION({ value: 'IL' }, SPAN({ text: 'Illinois' })),
                  OPTION({ value: 'IA' }, SPAN({ text: 'Iowa' })),
                  OPTION({ value: 'KS' }, SPAN({ text: 'Kansas' })),
                  OPTION({ value: 'KY' }, SPAN({ text: 'Kentucky' })),
                  OPTION({ value: 'LA' }, SPAN({ text: 'Louisiana' })),
                  OPTION({ value: 'MN' }, SPAN({ text: 'Minnesota' })),
                  OPTION({ value: 'MS' }, SPAN({ text: 'Mississippi' })),
                  OPTION({ value: 'MO' }, SPAN({ text: 'Missouri' })),
                  OPTION({ value: 'OK' }, SPAN({ text: 'Oklahoma' })),
                  OPTION({ value: 'SD' }, SPAN({ text: 'South Dakota' })),
                  OPTION({ value: 'TX' }, SPAN({ text: 'Texas' })),
                  OPTION({ value: 'TN' }, SPAN({ text: 'Tennessee' })),
                  OPTION({ value: 'WI' }, SPAN({ text: 'Wisconsin' })),
                  OPTION({ value: 'CT' }, SPAN({ text: 'Connecticut' })),
                  OPTION({ value: 'DE' }, SPAN({ text: 'Delaware' })),
                  OPTION({ value: 'FL' }, SPAN({ text: 'Florida' })),
                  OPTION({ value: 'GA' }, SPAN({ text: 'Georgia' })),
                  OPTION({ value: 'IN' }, SPAN({ text: 'Indiana' })),
                  OPTION({ value: 'ME' }, SPAN({ text: 'Maine' })),
                  OPTION({ value: 'MD' }, SPAN({ text: 'Maryland' })),
                  OPTION({ value: 'MA' }, SPAN({ text: 'Massachusetts' })),
                  OPTION({ value: 'MI' }, SPAN({ text: 'Michigan' })),
                  OPTION({ value: 'NH' }, SPAN({ text: 'New Hampshire' })),
                  OPTION({ value: 'NJ' }, SPAN({ text: 'New Jersey' })),
                  OPTION({ value: 'NY' }, SPAN({ text: 'New York' })),
                  OPTION({ value: 'NC' }, SPAN({ text: 'North Carolina' })),
                  OPTION({ value: 'OH' }, SPAN({ text: 'Ohio' })),
                  OPTION({ value: 'PA' }, SPAN({ text: 'Pennsylvania' })),
                  OPTION({ value: 'RI' }, SPAN({ text: 'Rhode Island' })),
                  OPTION({ value: 'SC' }, SPAN({ text: 'South Carolina' })),
                  OPTION({ value: 'VT' }, SPAN({ text: 'Vermont' })),
                  OPTION({ value: 'VA' }, SPAN({ text: 'Virginia' })),
                  OPTION({ value: 'WV' }, SPAN({ text: 'West Virginia' })),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'select2Multiple', class: 'form-label' }, SPAN({ text: 'Multiple' })),
                SELECT(
                  { id: 'select2Multiple', class: 'select2 form-select', multiple: 'multiple' },
                  OPTGROUP(
                    { label: 'Alaskan/Hawaiian Time Zone' },
                    OPTION({ value: 'AK' }, SPAN({ text: 'Alaska' })),
                    OPTION({ value: 'HI' }, SPAN({ text: 'Hawaii' })),
                  ),
                  OPTGROUP(
                    { label: 'Pacific Time Zone' },
                    OPTION({ value: 'CA' }, SPAN({ text: 'California' })),
                    OPTION({ value: 'NV' }, SPAN({ text: 'Nevada' })),
                    OPTION({ value: 'OR' }, SPAN({ text: 'Oregon' })),
                    OPTION({ value: 'WA' }, SPAN({ text: 'Washington' })),
                  ),
                  OPTGROUP(
                    { label: 'Mountain Time Zone' },
                    OPTION({ value: 'AZ' }, SPAN({ text: 'Arizona' })),
                    OPTION({ value: 'CO', selected: 'selected' }, SPAN({ text: 'Colorado' })),
                    OPTION({ value: 'ID' }, SPAN({ text: 'Idaho' })),
                    OPTION({ value: 'MT' }, SPAN({ text: 'Montana' })),
                    OPTION({ value: 'NE' }, SPAN({ text: 'Nebraska' })),
                    OPTION({ value: 'NM' }, SPAN({ text: 'New Mexico' })),
                    OPTION({ value: 'ND' }, SPAN({ text: 'North Dakota' })),
                    OPTION({ value: 'UT' }, SPAN({ text: 'Utah' })),
                    OPTION({ value: 'WY' }, SPAN({ text: 'Wyoming' })),
                  ),
                  OPTGROUP(
                    { label: 'Central Time Zone' },
                    OPTION({ value: 'AL' }, SPAN({ text: 'Alabama' })),
                    OPTION({ value: 'AR' }, SPAN({ text: 'Arkansas' })),
                    OPTION({ value: 'IL' }, SPAN({ text: 'Illinois' })),
                    OPTION({ value: 'IA' }, SPAN({ text: 'Iowa' })),
                    OPTION({ value: 'KS' }, SPAN({ text: 'Kansas' })),
                    OPTION({ value: 'KY' }, SPAN({ text: 'Kentucky' })),
                    OPTION({ value: 'LA' }, SPAN({ text: 'Louisiana' })),
                    OPTION({ value: 'MN' }, SPAN({ text: 'Minnesota' })),
                    OPTION({ value: 'MS' }, SPAN({ text: 'Mississippi' })),
                    OPTION({ value: 'MO' }, SPAN({ text: 'Missouri' })),
                    OPTION({ value: 'OK' }, SPAN({ text: 'Oklahoma' })),
                    OPTION({ value: 'SD' }, SPAN({ text: 'South Dakota' })),
                    OPTION({ value: 'TX' }, SPAN({ text: 'Texas' })),
                    OPTION({ value: 'TN' }, SPAN({ text: 'Tennessee' })),
                    OPTION({ value: 'WI' }, SPAN({ text: 'Wisconsin' })),
                  ),
                  OPTGROUP(
                    { label: 'Eastern Time Zone' },
                    OPTION({ value: 'CT' }, SPAN({ text: 'Connecticut' })),
                    OPTION({ value: 'DE' }, SPAN({ text: 'Delaware' })),
                    OPTION({ value: 'FL', selected: 'selected' }, SPAN({ text: 'Florida' })),
                    OPTION({ value: 'GA' }, SPAN({ text: 'Georgia' })),
                    OPTION({ value: 'IN' }, SPAN({ text: 'Indiana' })),
                    OPTION({ value: 'ME' }, SPAN({ text: 'Maine' })),
                    OPTION({ value: 'MD' }, SPAN({ text: 'Maryland' })),
                    OPTION({ value: 'MA' }, SPAN({ text: 'Massachusetts' })),
                    OPTION({ value: 'MI' }, SPAN({ text: 'Michigan' })),
                    OPTION({ value: 'NH' }, SPAN({ text: 'New Hampshire' })),
                    OPTION({ value: 'NJ' }, SPAN({ text: 'New Jersey' })),
                    OPTION({ value: 'NY' }, SPAN({ text: 'New York' })),
                    OPTION({ value: 'NC' }, SPAN({ text: 'North Carolina' })),
                    OPTION({ value: 'OH' }, SPAN({ text: 'Ohio' })),
                    OPTION({ value: 'PA' }, SPAN({ text: 'Pennsylvania' })),
                    OPTION({ value: 'RI' }, SPAN({ text: 'Rhode Island' })),
                    OPTION({ value: 'SC' }, SPAN({ text: 'South Carolina' })),
                    OPTION({ value: 'VT' }, SPAN({ text: 'Vermont' })),
                    OPTION({ value: 'VA' }, SPAN({ text: 'Virginia' })),
                    OPTION({ value: 'WV' }, SPAN({ text: 'West Virginia' })),
                  ),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'select2Disabled', class: 'form-label' }, SPAN({ text: 'Disabled' })),
                SELECT(
                  { id: 'select2Disabled', class: 'select2 form-select', disabled: 'disabled' },
                  OPTION({ value: '1' }, SPAN({ text: 'Option1' })),
                  OPTION({ value: '2', selected: 'selected' }, SPAN({ text: 'Option2' })),
                  OPTION({ value: '3' }, SPAN({ text: 'Option3' })),
                  OPTION({ value: '4' }, SPAN({ text: 'Option4' })),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'select2Icons', class: 'form-label' }, SPAN({ text: 'Icons' })),
                SELECT(
                  { id: 'select2Icons', class: 'select2-icons form-select' },
                  OPTGROUP(
                    { label: 'Services' },
                    OPTION(
                      { value: 'wordpress2', 'data-icon': 'bx bxl-wordpress', selected: 'selected' },
                      SPAN({ text: 'WordPress' }),
                    ),
                    OPTION({ value: 'codepen', 'data-icon': 'bx bxl-codepen' }, SPAN({ text: 'Codepen' })),
                    OPTION({ value: 'drupal', 'data-icon': 'bx bxl-drupal' }, SPAN({ text: 'Drupal' })),
                    OPTION({ value: 'pinterest2', 'data-icon': 'bx bxl-css3' }, SPAN({ text: 'CSS3' })),
                    OPTION({ value: 'html5', 'data-icon': 'bx bxl-html5' }, SPAN({ text: 'HTML5' })),
                  ),
                  OPTGROUP(
                    { label: 'File types' },
                    OPTION({ value: 'pdf', 'data-icon': 'bx bxs-file-pdf' }, SPAN({ text: 'PDF' })),
                    OPTION({ value: 'word', 'data-icon': 'bx bxs-file-doc' }, SPAN({ text: 'Word' })),
                    OPTION({ value: 'excel', 'data-icon': 'bx bxs-file-json' }, SPAN({ text: 'JSON' })),
                    OPTION({ value: 'facebook', 'data-icon': 'bx bxl-facebook' }, SPAN({ text: 'Facebook' })),
                  ),
                  OPTGROUP(
                    { label: 'Browsers' },
                    OPTION({ value: 'chrome', 'data-icon': 'bx bxl-chrome' }, SPAN({ text: 'Chrome' })),
                    OPTION({ value: 'firefox', 'data-icon': 'bx bxl-firefox' }, SPAN({ text: 'Firefox' })),
                    OPTION({ value: 'safari', 'data-icon': 'bx bxl-edge' }, SPAN({ text: 'Edge' })),
                    OPTION({ value: 'opera', 'data-icon': 'bx bxl-opera' }, SPAN({ text: 'Opera' })),
                    OPTION({ value: 'IE', 'data-icon': 'bx bxl-internet-explorer' }, SPAN({ text: 'IE' })),
                  ),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'select2Primary', class: 'form-label' }, SPAN({ text: 'Primary' })),
                DIV(
                  { class: 'select2-primary' },
                  SELECT(
                    { id: 'select2Primary', class: 'select2 form-select', multiple: 'multiple' },
                    OPTION({ value: '1', selected: 'selected' }, SPAN({ text: 'Option1' })),
                    OPTION({ value: '2', selected: 'selected' }, SPAN({ text: 'Option2' })),
                    OPTION({ value: '3' }, SPAN({ text: 'Option3' })),
                    OPTION({ value: '4' }, SPAN({ text: 'Option4' })),
                  ),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'select2Success', class: 'form-label' }, SPAN({ text: 'Success' })),
                DIV(
                  { class: 'select2-success' },
                  SELECT(
                    { id: 'select2Success', class: 'select2 form-select', multiple: 'multiple' },
                    OPTION({ value: '1', selected: 'selected' }, SPAN({ text: 'Option1' })),
                    OPTION({ value: '2', selected: 'selected' }, SPAN({ text: 'Option2' })),
                    OPTION({ value: '3' }, SPAN({ text: 'Option3' })),
                    OPTION({ value: '4' }, SPAN({ text: 'Option4' })),
                  ),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'select2Info', class: 'form-label' }, SPAN({ text: 'Info' })),
                DIV(
                  { class: 'select2-info' },
                  SELECT(
                    { id: 'select2Info', class: 'select2 form-select', multiple: 'multiple' },
                    OPTION({ value: '1', selected: 'selected' }, SPAN({ text: 'Option1' })),
                    OPTION({ value: '2', selected: 'selected' }, SPAN({ text: 'Option2' })),
                    OPTION({ value: '3' }, SPAN({ text: 'Option3' })),
                    OPTION({ value: '4' }, SPAN({ text: 'Option4' })),
                  ),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'select2Warning', class: 'form-label' }, SPAN({ text: 'Warning' })),
                DIV(
                  { class: 'select2-warning' },
                  SELECT(
                    { id: 'select2Warning', class: 'select2 form-select', multiple: 'multiple' },
                    OPTION({ value: '1', selected: 'selected' }, SPAN({ text: 'Option1' })),
                    OPTION({ value: '2', selected: 'selected' }, SPAN({ text: 'Option2' })),
                    OPTION({ value: '3' }, SPAN({ text: 'Option3' })),
                    OPTION({ value: '4' }, SPAN({ text: 'Option4' })),
                  ),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4 mb-md-0' },
                LABEL({ for: 'select2Danger', class: 'form-label' }, SPAN({ text: 'Danger' })),
                DIV(
                  { class: 'select2-danger' },
                  SELECT(
                    { id: 'select2Danger', class: 'select2 form-select', multiple: 'multiple' },
                    OPTION({ value: '1', selected: 'selected' }, SPAN({ text: 'Option1' })),
                    OPTION({ value: '2', selected: 'selected' }, SPAN({ text: 'Option2' })),
                    OPTION({ value: '3' }, SPAN({ text: 'Option3' })),
                    OPTION({ value: '4' }, SPAN({ text: 'Option4' })),
                  ),
                ),
              ),
              DIV(
                { class: 'col-md-6' },
                LABEL({ for: 'select2Dark', class: 'form-label' }, SPAN({ text: 'Dark' })),
                DIV(
                  { class: 'select2-dark' },
                  SELECT(
                    { id: 'select2Dark', class: 'select2 form-select', multiple: 'multiple' },
                    OPTION({ value: '1', selected: 'selected' }, SPAN({ text: 'Option1' })),
                    OPTION({ value: '2', selected: 'selected' }, SPAN({ text: 'Option2' })),
                    OPTION({ value: '3' }, SPAN({ text: 'Option3' })),
                    OPTION({ value: '4' }, SPAN({ text: 'Option4' })),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      DIV(
        { class: 'col-12' },
        DIV(
          { class: 'card mb-4' },
          H5({ class: 'card-header' }, SPAN({ text: 'Tagify' })),
          DIV(
            { class: 'card-body' },
            DIV(
              { class: 'row' },
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'TagifyBasic', class: 'form-label' }, SPAN({ text: 'Basic' })),
                INPUT({
                  id: 'TagifyBasic',
                  class: 'form-control',
                  name: 'TagifyBasic',
                  value: 'Tag1, Tag2, Tag3',
                }),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'TagifyReadonly', class: 'form-label' }, SPAN({ text: 'Readonly' })),
                INPUT({
                  id: 'TagifyReadonly',
                  class: 'form-control',
                  readonly: 'readonly',
                  value: 'Tag1, Tag2, Tag3',
                }),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL(
                  { for: 'TagifyCustomInlineSuggestion', class: 'form-label' },
                  SPAN({ text: 'Custom Inline Suggestions' }),
                ),
                INPUT({
                  id: 'TagifyCustomInlineSuggestion',
                  name: 'TagifyCustomInlineSuggestion',
                  class: 'form-control',
                  placeholder: 'select technologies',
                  value: 'css, html, javascript',
                }),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL(
                  { for: 'TagifyCustomListSuggestion', class: 'form-label' },
                  SPAN({ text: 'Custom List Suggestions' }),
                ),
                INPUT({
                  id: 'TagifyCustomListSuggestion',
                  name: 'TagifyCustomListSuggestion',
                  class: 'form-control',
                  placeholder: 'select technologies',
                  value: 'css, html, php',
                }),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'TagifyUserList', class: 'form-label' }, SPAN({ text: 'Users List' })),
                INPUT({
                  id: 'TagifyUserList',
                  name: 'TagifyUserList',
                  class: 'form-control',
                  value: 'abatisse2@nih.gov, Justinian Hattersley',
                }),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'TagifyEmailList', class: 'form-label d-block' }, SPAN({ text: 'Email List' })),
                INPUT({
                  id: 'TagifyEmailList',
                  class: 'tagify-email-list',
                  value: 'some56.name@website.com',
                }),
                BUTTON(
                  { type: 'button', class: 'btn rounded-pill btn-icon btn-outline-primary mt-1' },
                  SPAN({ class: 'tf-icons bx bx-plus' }),
                ),
              ),
            ),
          ),
        ),
      ),
      DIV(
        { class: 'col-12' },
        DIV(
          { class: 'card mb-4' },
          H5({ class: 'card-header' }, SPAN({ text: 'Typeahead' })),
          DIV(
            { class: 'card-body' },
            DIV(
              { class: 'row' },
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'TypeaheadBasic', class: 'form-label' }, SPAN({ text: 'Basic' })),
                INPUT({
                  id: 'TypeaheadBasic',
                  class: 'form-control typeahead',
                  type: 'text',
                  autocomplete: 'off',
                  placeholder: 'Enter states from USA',
                }),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL(
                  { for: 'TypeaheadBloodHound', class: 'form-label' },
                  SPAN({ text: 'BloodHound (Suggestion Engine)' }),
                ),
                INPUT({
                  id: 'TypeaheadBloodHound',
                  class: 'form-control typeahead-bloodhound',
                  type: 'text',
                  autocomplete: 'off',
                  placeholder: 'Enter states from USA',
                }),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'TypeaheadPrefetch', class: 'form-label' }, SPAN({ text: 'Prefetch' })),
                INPUT({
                  id: 'TypeaheadPrefetch',
                  class: 'form-control typeahead-prefetch',
                  type: 'text',
                  autocomplete: 'off',
                  placeholder: 'Enter states from USA',
                }),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'TypeaheadSuggestions', class: 'form-label' }, SPAN({ text: 'Default Suggestions' })),
                INPUT({
                  id: 'TypeaheadSuggestions',
                  class: 'form-control typeahead-default-suggestions',
                  type: 'text',
                  autocomplete: 'off',
                }),
              ),
              DIV(
                { class: 'col-md-6 mb-4 mb-md-0' },
                LABEL({ for: 'TypeaheadCustom', class: 'form-label' }, SPAN({ text: 'Custom Template' })),
                INPUT({
                  id: 'TypeaheadCustom',
                  class: 'form-control typeahead-custom-template',
                  type: 'text',
                  autocomplete: 'off',
                  placeholder: 'Search For Oscar Winner',
                }),
              ),
              DIV(
                { class: 'col-md-6' },
                LABEL({ for: 'TypeaheadMultipleDataset', class: 'form-label' }, SPAN({ text: 'Multiple Datasets' })),
                INPUT({
                  id: 'TypeaheadMultipleDataset',
                  class: 'form-control typeahead-multi-datasets',
                  type: 'text',
                  autocomplete: 'off',
                }),
              ),
            ),
          ),
        ),
      ),
      DIV(
        { class: 'col-12' },
        DIV(
          { class: 'card' },
          H5({ class: 'card-header' }, SPAN({ text: 'Bootstrap Select' })),
          DIV(
            { class: 'card-body' },
            DIV(
              { class: 'row' },
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'selectpickerBasic', class: 'form-label' }, SPAN({ text: 'Basic' })),
                SELECT(
                  { id: 'selectpickerBasic', class: 'selectpicker w-100', 'data-style': 'btn-default' },
                  OPTION({}, SPAN({ text: 'Rocky' })),
                  OPTION({}, SPAN({ text: 'Pulp Fiction' })),
                  OPTION({}, SPAN({ text: 'The Godfather' })),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'selectpickerGroups', class: 'form-label' }, SPAN({ text: 'Groups' })),
                SELECT(
                  {
                    id: 'selectpickerGroups',
                    class: 'selectpicker w-100',
                    'data-style': 'btn-default',
                  },
                  OPTGROUP(
                    { label: 'Movies' },
                    OPTION({}, SPAN({ text: 'Rocky' })),
                    OPTION({}, SPAN({ text: 'Pulp Fiction' })),
                    OPTION({}, SPAN({ text: 'The Godfather' })),
                  ),
                  OPTGROUP(
                    { label: 'Series' },
                    OPTION({}, SPAN({ text: 'Breaking Bad' })),
                    OPTION({}, SPAN({ text: 'Black Mirror' })),
                    OPTION({}, SPAN({ text: 'Money Heist' })),
                  ),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'selectpickerMultiple', class: 'form-label' }, SPAN({ text: 'Multiple' })),
                SELECT(
                  {
                    id: 'selectpickerMultiple',
                    class: 'selectpicker w-100',
                    'data-style': 'btn-default',
                    multiple: 'multiple',
                    'data-icon-base': 'bx',
                    'data-tick-icon': 'bx-check text-primary',
                  },
                  OPTION({}, SPAN({ text: 'Rocky' })),
                  OPTION({}, SPAN({ text: 'Pulp Fiction' })),
                  OPTION({}, SPAN({ text: 'The Godfather' })),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'selectpickerLiveSearch', class: 'form-label' }, SPAN({ text: 'Live Search' })),
                SELECT(
                  {
                    id: 'selectpickerLiveSearch',
                    class: 'selectpicker w-100',
                    'data-style': 'btn-default',
                    'data-live-search': 'true',
                  },
                  OPTION({ 'data-tokens': 'ketchup mustard' }, SPAN({ text: 'Hot Dog, Fries and a Soda' })),
                  OPTION({ 'data-tokens': 'mustard' }, SPAN({ text: 'Burger, Shake and a Smile' })),
                  OPTION({ 'data-tokens': 'frosting' }, SPAN({ text: 'Sugar, Spice and all things nice' })),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'selectpickerIcons', class: 'form-label' }, SPAN({ text: 'Icons' })),
                SELECT(
                  {
                    class: 'selectpicker w-100 show-tick',
                    id: 'selectpickerIcons',
                    'data-icon-base': 'bx',
                    'data-tick-icon': 'bx-check',
                    'data-style': 'btn-default',
                  },
                  OPTION({ 'data-icon': 'bx bxl-instagram' }, SPAN({ text: 'Instagram' })),
                  OPTION({ 'data-icon': 'bx bxl-pinterest-alt' }, SPAN({ text: 'Pinterest' })),
                  OPTION({ 'data-icon': 'bx bxl-twitch' }, SPAN({ text: 'Twitch' })),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'selectpickerSubtext', class: 'form-label' }, SPAN({ text: 'Subtext' })),
                SELECT(
                  {
                    id: 'selectpickerSubtext',
                    class: 'selectpicker w-100',
                    'data-style': 'btn-default',
                    'data-show-subtext': 'true',
                  },
                  OPTION({ 'data-subtext': 'Framework' }, SPAN({ text: 'React' })),
                  OPTION({ 'data-subtext': 'Styles' }, SPAN({ text: 'Sass' })),
                  OPTION({ 'data-subtext': 'Markup' }, SPAN({ text: 'HTML' })),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'selectpickerSelection', class: 'form-label' }, SPAN({ text: 'Selection Limit' })),
                SELECT(
                  {
                    id: 'selectpickerSelection',
                    class: 'selectpicker w-100',
                    'data-style': 'btn-default',
                    multiple: 'multiple',
                    'data-max-options': '2',
                  },
                  OPTION({}, SPAN({ text: 'Rocky' })),
                  OPTION({}, SPAN({ text: 'Pulp Fiction' })),
                  OPTION({}, SPAN({ text: 'The Godfather' })),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL(
                  { for: 'selectpickerSelectDeselect', class: 'form-label' },
                  SPAN({ text: 'Select / Deselect All' }),
                ),
                SELECT(
                  {
                    id: 'selectpickerSelectDeselect',
                    class: 'selectpicker w-100',
                    'data-style': 'btn-default',
                    multiple: 'multiple',
                    'data-actions-box': 'true',
                  },
                  OPTION({}, SPAN({ text: 'Rocky' })),
                  OPTION({}, SPAN({ text: 'Pulp Fiction' })),
                  OPTION({}, SPAN({ text: 'The Godfather' })),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'selectpickerDivider', class: 'form-label' }, SPAN({ text: 'Divider' })),
                SELECT(
                  {
                    id: 'selectpickerDivider',
                    class: 'selectpicker w-100',
                    'data-style': 'btn-default',
                  },
                  OPTION({}, SPAN({ text: 'Rocky' })),
                  OPTION({ 'data-divider': 'true' }, SPAN({ text: 'divider' })),
                  OPTION({}, SPAN({ text: 'Pulp Fiction' })),
                  OPTION({}, SPAN({ text: 'The Godfather' })),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4' },
                LABEL({ for: 'selectpickerHeader', class: 'form-label' }, SPAN({ text: 'Header' })),
                SELECT(
                  {
                    id: 'selectpickerHeader',
                    class: 'selectpicker w-100',
                    'data-style': 'btn-default',
                    'data-header': 'Select a Movie',
                  },
                  OPTION({}, SPAN({ text: 'Rocky' })),
                  OPTION({}, SPAN({ text: 'Pulp Fiction' })),
                  OPTION({}, SPAN({ text: 'The Godfather' })),
                ),
              ),
              DIV(
                { class: 'col-md-6 mb-4 mb-md-0' },
                LABEL({ for: 'selectpickerDisabled', class: 'form-label' }, SPAN({ text: 'Disabled' })),
                SELECT(
                  {
                    id: 'selectpickerDisabled',
                    class: 'selectpicker w-100',
                    'data-style': 'btn-default',
                    disabled: 'disabled',
                  },
                  OPTION({}, SPAN({ text: 'Rocky' })),
                  OPTION({}, SPAN({ text: 'Pulp Fiction' })),
                  OPTION({}, SPAN({ text: 'The Godfather' })),
                ),
              ),
              DIV(
                { class: 'col-md-6' },
                LABEL({ for: 'selectpickerDisabledOptions', class: 'form-label' }, SPAN({ text: 'Disabled Options' })),
                SELECT(
                  {
                    id: 'selectpickerDisabledOptions',
                    class: 'selectpicker w-100',
                    'data-style': 'btn-default',
                  },
                  OPTION({}, SPAN({ text: 'Rocky' })),
                  OPTION({ disabled: 'disabled' }, SPAN({ text: 'Pulp Fiction' })),
                  OPTION({}, SPAN({ text: 'The Godfather' })),
                ),
              ),
            ),
          ),
        ),
      ),
    ),
  ],
  on: {
    load: (el) => {
      window.loadRes('theme/sneat/forms-selects.js');
      window.loadRes('theme/sneat/forms-tagify.js');
      window.loadRes('theme/sneat/forms-typeahead.js');
    },
  },
});
